---
# tasks file for hadoop_slaves
- name: Copying main configuration files
  copy: src=core-site.xml dest=/etc/hadoop/core-site.xml group=hadoop
- name: Copying main configuration files
  copy: src=hdfs-site.xml dest=/etc/hadoop/hdfs-site.xml group=hadoop
- name: Copying main configuration files
  copy: src=mapred-site.xml dest=/etc/hadoop/mapred-site.xml group=hadoop
- name: Copying main configuration files
  copy: src=yarn-site.xml dest=/etc/hadoop/yarn-site.xml group=hadoop
...
